//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int Id { get; set; }
        public string Descriptions { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string Types { get; set; }
    }
}
